apiVersion: 1

datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://statsd:80
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s" 