# WaveCore Quick Development Configuration
# Untuk development dan debugging cepat

global:
  environment: "development"
  log_level: "info"
  output_dir: "./output"
  timestamp_format: "%Y-%m-%d %H:%M:%S"
  timezone: "UTC"

hardware:
  baseline:
    cpu: "Generic CPU"
    cores: 4
    threads: 8
    ram_gb: 8
    os: "Linux"
    blas: "OpenBLAS"
  limits:
    max_cpu_usage: 80.0
    max_memory_usage: 70.0
    max_disk_usage: 90.0
    max_test_duration_hours: 1

test_categories:
  functional:
    enabled: true
    description: "Functional tests for quick development"
    tests: ["hydrostatics"]
    timeout_minutes: 5
    retry_count: 1
  performance:
    enabled: false
    description: "Performance tests"
    tests: []
    timeout_minutes: 10
    retry_count: 2
  extensions:
    enabled: false
    description: "Extension tests"
    tests: []
    timeout_minutes: 10
    retry_count: 2
  validation:
    enabled: false
    description: "Validation tests"
    tests: []
    timeout_minutes: 10
    retry_count: 2

stress_testing:
  enabled: false
  description: "Stress testing disabled for quick development"
  slo:
    p50_latency_ms: 500.0
    p95_latency_ms: 2000.0
    p99_latency_ms: 5000.0
    error_rate_percent: 20.0
    throughput_sps: 10.0
  stop_conditions:
    p99_latency_ms: 10000.0
    error_rate_percent: 50.0
    memory_usage_percent: 90.0
    cpu_usage_percent: 95.0
    consecutive_failures: 3
  load_patterns:
    linear_ramp:
      enabled: false
      description: "Linear ramp load pattern"
      phases: []
    step_load:
      enabled: false
      description: "Step load pattern"
      phases: []
    wave_load:
      enabled: false
      description: "Wave load pattern"
      phases: []
    stress_to_failure:
      enabled: false
      description: "Stress to failure pattern"
      phases: []

msr_search:
  enabled: false
  algorithm: "binary_search"
  description: "MSR search disabled for quick development"
  aimd:
    additive_increase: 0.1
    multiplicative_decrease: 0.5
    interval_seconds: 30
    convergence_threshold: 0.1
  binary_search:
    max_iterations: 10
    convergence_threshold: 0.1
    stability_periods: 3
  criteria:
    p99_latency_ms: 1000.0
    error_rate_percent: 5.0
    stability_duration_minutes: 5
  search_space:
    load_multipliers: [1.0, 2.0]
    duration_minutes: [5, 10]
    step_size: 0.5
  convergence:
    max_iterations: 10
    tolerance: 0.1
    min_improvement: 0.05
  validation:
    confidence_threshold: 0.8
    min_samples: 3
    max_outliers: 1

monitoring:
  enabled: true
  description: "Basic monitoring for quick development"
  metrics:
    latency:
      enabled: true
      collection_interval_seconds: 5
      percentiles: [50, 95, 99]
    throughput:
      enabled: true
      collection_interval_seconds: 5
      percentiles: null
    resource_usage:
      enabled: true
      metrics: ["cpu", "memory", "disk"]
      collection_interval_seconds: 5
    errors:
      enabled: true
      collection_interval_seconds: 5
      percentiles: null
  profiling:
    enabled: false
    tools: []
    collection_interval_seconds: 10
  logging:
    level: "info"
    format: "json"
    rotation:
      max_size_mb: 100
      max_files: 10
    destinations: ["file", "console"]

test_matrix:
  mesh_sizes:
    - name: "small"
      panels: 50
      description: "Very small mesh for quick tests"
  frequencies:
    - name: "low"
      range: [0.1, 0.5]
      count: 5
  problem_types: ["hydrostatics"]

reporting:
  enabled: true
  formats: ["json", "markdown"]
  sections: ["summary", "metrics"]
  visualizations: ["charts"]
  export:
    include_raw_data: false
    include_charts: true
    include_logs: false
    compression: "none" 